name: Ruff Check
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - name: Install Poetry
      uses: snok/install-poetry@v1.3
      with:
        version: 1.8.2
    - name: Install dependencies with Poetry
      run: poetry install
    - name: Run Ruff Linting
      run: poetry run ruff check .
